/**
 * Writes the contract ABIs the web app needs into src/lib/chain/abis.ts as `as const`
 * literals, so the Next.js build never depends on the gitignored artifacts folder.
 * Run after `hardhat compile`: npm run contracts:abis
 */
import { readFileSync, writeFileSync } from "node:fs"

const contracts = ["ReadingRegistry", "RECToken", "EnergyMarket"] as const

const parts = contracts.map((name) => {
  const artifact = JSON.parse(readFileSync(`artifacts/contracts/${name}.sol/${name}.json`, "utf8")) as {
    abi: unknown[]
  }
  const id = name === "RECToken" ? "recToken" : name[0].toLowerCase() + name.slice(1)
  return `export const ${id}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
})

writeFileSync(
  "src/lib/chain/abis.ts",
  `// Generated by scripts/export-abis.ts from Hardhat artifacts. Do not edit by hand.\n\n${parts.join("\n")}`,
)
console.log(`Wrote ${contracts.length} ABIs to src/lib/chain/abis.ts`)
